[meta]
name     = "Better Room Manager"
author   = "XertroV"
category = "Club"
version  = "0.3.4"
siteid   = 312

[script]
#__DEFINES__
dependencies = ["NadeoServices"]
exports = ["BRM_Exports/Exports.as"]
shared_exports = ["BRM_Exports/Shared.as"]
module = "BRM"
